name: Nephele Test to Submit paired FASTQ files for 16S Amplicon Data
on: workflow_dispatch

jobs:
  NepheleJobSubmission:

    runs-on: ubuntu-latest
    defaults:
       run:
      #  folder working directory.
        working-directory: Tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: start selenium docker grid set up to submit jobs in Nephele
      run: docker-compose -f "docker-compose.yaml" up -d
    
    - name: Run Tests
      run: mvn clean test
      
    - name: JoSubmissionTestResults
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
          name: JobSubmissionResults
          path: |
            Tests/target/cucumber.html
            Tests/outputResults
 
    - name: send Email if Test(s) fail
      if:   failure()
      uses: dawidd6/action-send-mail@v3
      with:
    # mail server settings
       server_address: smtp.gmail.com
       server_port: 465
    # user credentials
       username: ${{ secrets.EMAIL_USERNAME }}
       password: ${{ secrets.EMAIL_PASSWORD }}
    # email subject
       subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # email body as text
       body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    # comma-separated string, send email to
       to: krishnavenikaladi@gmail.com,krishnaveni.kaladi@nih.gov
    # from email name
       from: TestingTeam
       attachments:  Tests/outputResults,Tests/target/cucumber.html
    # Optional priority: 'high', 'normal' (default) or 'low'
       priority: medium

